.TH findopt 3 "December 1, 2017" "" "GNU argparser"

.SH НАЗВАНИЕ
findopt \- функция, осуществляющая поиск опций по имени

.SH СИНТАКСИС
.B #include "argparser.h"
.br
.B int findopt(OPTARG opt, const char *o, char **value);
.br

.SH ОПИСАНИЕ
Функция принимает следующие аргументы:
.PP
\fB OPTARG opt \fR
.RS 4
Структура, полученная от функции \fB argparse \fR
.RE
\fB const char *o \fR
.RS
Название опции
.RE
\fB char **value \fR
.RS 4
Указатель на указатель на строку, куда будет помещаться указатель на значение опции.
.RE
.SH "КОД ВЫХОДА"
В случае успешного поиска возвращает 0. В противном случае -1.

.SH "ВОЗВРАЩАЕМОЕ ЗНАЧЕНИЕ"
В случае, если искомая опция имеет параметр, указатель на него возвращается через \fB value \fR

.SH "СМОТРИТЕ ТАКЖЕ"
argparse(3), argclean(3)

